export const PortfolioInfo = [
  {
    title: "Ssafy-Shopper",
    subTitle: "알레르기가 있는 사람들을 위한 건강먹거리 쇼핑몰",
    video: "video/Ssafy-Shopper.mp4",
    date: "2019.12.10. ~ 2019.12.16. (1주)",
    work: [
      "로그인, 회원가입 UI / UX 구현",
      "장바구니 UI / UX 구현",
      "Q&A 게시판 UI / UX 구현",
      "식품 안전나라 식품 영양 공공데이터 파싱",
      "식품 리스트 출력",
      "알레르기, 품절에 따른 이미지 처리",
      "식품별 영양정보 차트 출력",
    ],
    tag: [
      ["2인(기여도 55%)", "blue"],
      ["Front-End(100%)", "red"],
      ["Spring", "green"],
      ["Vue.js", "light-green"],
      ["HTML", "orange"],
      ["CSS", "blue"],
      ["JavaScript", "purple"],
      ["BootStrap", "dark-blue"],
      ["SQL", "yellow"],
    ],
  },
  {
    title: "Newspace",
    subTitle: "관심 키워드의 뉴스만 모아볼수 있는 사이트",
    video: "video/Newspace.mp4",
    date: "2020.01. ~ 2020.02. (6주)",
    work: [
      "로그인, 회원가입 UI / UX 구현",
      "JWT를 이용한 데이터 암호화 구현",
      "Vuex를 이용한 실시간 상태관리",
      "소셜로그인 구현 (Firebase이용)",
      "STOMP를 이용한 메일링시스템 구현 및 UI / UX 구현",
      "STMP를 이용한 채팅시스템 구현 및 UI / UX 구현",
    ],
    tag: [
      ["4인(기여도 30%)", "blue"],
      ["Back-End(2인 중 50%)", "red"],
      ["Front-End(3인 중 20%)", "red"],
      ["Spring", "green"],
      ["Vue.js", "light-green"],
      ["HTML", "orange"],
      ["CSS", "blue"],
      ["JavaScript", "purple"],
      ["Vuetify", "dark-blue"],
      ["SQL", "yellow"],
    ],
  },
  {
    title: "냉장고를 부탁해",
    subTitle: "AI로 냉장고에 있는 식재료를 식별하고 레시피를 추천해주는 서비스",
    video: "video/냉장고를부탁해.mp4",
    date: "2020.03. ~ 2020.04. (5주)",
    work: [
      "레시피 목록 UI / UX 구현",
      "레시피 재료선택 UI / UX 구현",
      "레시피 상세페이지 UI / UX 구현",
      "인식률에 따른 재료 아이콘 색깔조정",
      "Vuex를 이용한 실시간 상태관리",
      "PWA 적용",
    ],
    tag: [
      ["6인 기여도 15%", "blue"],
      ["Front-End(2인 중 50%)", "red"],
      ["Vue.js", "light-green"],
      ["HTML", "orange"],
      ["CSS", "blue"],
      ["JavaScript", "purple"],
    ],
  },
  {
    title: "IT FOR YOU",
    subTitle: "CS지식과 면접대비를 도와주는 사이트",
    video: "video/ITFORYOU.mov",
    date: "2020.05. ~ 2020.06. (5주)",
    work: [
      "메인화면 UI / UX 구현",
      "네비게이션 UI / UX 구현",
      "단어장 UI / UX 구현",
      "오답노트 UI / UX 구현",
      "문제풀이 알고리즘 구현",
      "자신의 강점, 틀린문제 분석 차트 출력",
      "transform 애니메이션 적용",
      "Vuex를 이용한 상태관리",
      "PWA 적용",
    ],
    tag: [
      ["5인 기여도 30%", "blue"],
      ["Front-End(2인 중 50%)", "red"],
      ["Vue.js", "light-green"],
      ["HTML", "orange"],
      ["CSS", "blue"],
      ["JavaScript", "purple"],
    ],
  },
  {
    title: "Unithis",
    subTitle: "물품 교환 플랫폼 서비스",
    video: "video/Unithis.mp4",
    date: "2020.08. ~ 2020.08. (4주)",
    repositoryLink: "https://github.com/AfterSSAFY/Unithis",
    work: [
      "회원가입 및 로그인 UI / UX 구현",
      "메인화면 UI / UX 구현",
      "상품등록 UI / UX 구현",
      "상품상세 UI / UX 구현",
      "채팅 UI / UX 구현",
      "Redux를 이용한 상태관리",
      "TypeScript 적용",
      "redux-thunk를 이용한 비동기 API요청 처리",
      "파일업로드 구현",
      "라우터 구현",
      "무한스크롤 구현",
      "주소 필터링 알고리즘 구현",
    ],
    tag: [
      ["3인 기여도 50%", "blue"],
      ["Front-End (100%)", "red"],
      ["React.js", "light-green"],
      ["HTML", "orange"],
      ["CSS", "blue"],
      ["TypeScript", "purple"],
    ],
  },
  {
    title: "프로그래머스 클론",
    subTitle: "React 학습용 클론 프로젝트",
    date: "2020.09. ~ 2020.10. (5주)",
    image: "./images/프로그래머스.png",
    repositoryLink: "https://github.com/gong-clone/programmers-clone",
    work: [
      "채용프로그램 UI / UX 구현",
      "프로그래머스 이벤트 배너 UI / UX 구현",
      "Swiper 구현",
      "Carousel 구현",
      "컴포넌트 단위 Emotion 적용",
      "컴포넌트 단위 StoryBook 적용",
      "코드리뷰 및 칸반보드 활용",
      "FirebaseStore 이용",
    ],
    tag: [
      ["3인(기여도 35%)", "blue"],
      ["Front-End(100%)", "red"],
      ["React.js", "green"],
      ["HTML", "orange"],
      ["Emotion", "blue"],
      ["TypeScript", "purple"],
      ["StoryBook", "dark-blue"],
      ["FirebaseStore", "yellow"],
    ],
  },
];

export const PortfolioInfoLength = PortfolioInfo.length;
